In [1]:
from config import db

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

QUERY = '''
    SELECT r.record_id, o.ops_kode, o.ops_version, r.icd_three, r.geschlecht, r.alter_in_jahren_am_aufnahmetag, 
        r.clinic_id, o.ops_datum, r.aufnahmedatum,  r.aufnahmeanlass, s.aufnahmegrund, 
        ABS(DATEDIFF(r.aufnahmedatum, r.entlassungsdatum))
    FROM icd_records r 
    JOIN ops o 
    ON r.record_id = o.record_id
    JOIN records s
    ON r.record_id = s.record_id
    WHERE r.diagnoseart = 'HD' AND r.alter_in_jahren_am_aufnahmetag >=0 AND r.aufnahmegrund > 100
--    LIMIT 100
'''

DATAFRAME = pd.read_sql(QUERY, con=db)

In [2]:
DATAFRAME = DATAFRAME.rename(columns = {'ABS(DATEDIFF(r.aufnahmedatum, r.entlassungsdatum))':'absolute_verweildauer_in_tagen'})

DATAFRAME['wochentag_ops_datum'] = pd.DatetimeIndex(DATAFRAME['ops_datum']).weekday
DATAFRAME['wochentag_aufnahmedatum'] = pd.DatetimeIndex(DATAFRAME['aufnahmedatum']).weekday  # The day of the week with Monday=0, Sunday=6



## DataFrame infomation
print(DATAFRAME.ndim)  # number of dimensions the DATAFRAME has -> 2
print(DATAFRAME.shape)  # shape of the DATAFRAME                -> (1020592, 14)
print(DATAFRAME.size)  # total entries in the DATAFRAME         -> 14288288 features and targets
#print(DATAFRAME.axes)  # returns axes labels                   -> Index(['record_id', 'ops_kode', 'ops_version', 'icd_three',
#                                                                 'geschlecht', 'alter_in_jahren_am_aufnahmetag', 'clinic_id',
#                                                                 'ops_datum', 'aufnahmedatum', 'aufnahmeanlass', 'aufnahmegrund',
#                                                                 'absolute_verweildauer_in_tagen', 'wochentag_ops_datum', 'wochentag_aufnahmedatum']

## Check for/dropping duplicates
DATAFRAME.drop_duplicates(inplace=True)  # (1020894, 13)  ->  (996861, 14)
print(DATAFRAME.shape) 

# Create .csv to settle the data
DATAFRAME.to_csv('LoS_data.csv', index=False)
DATAFRAME
#DATAFRAME= pd.read_csv('LoS_data.csv')

2
(1020592, 14)
14288288
(996861, 14)

,record_id,ops_kode,ops_version,icd_three,geschlecht,alter_in_jahren_am_aufnahmetag,clinic_id,ops_datum,aufnahmedatum,aufnahmeanlass,aufnahmegrund,absolute_verweildauer_in_tagen,wochentag_ops_datum,wochentag_aufnahmedatum
0,1,162000,2011,A19,m,34,1,2011-12-03 11:24:00,2011-12-01 16:21:00,E,101,228.0,5,3.0
1,1,3202,2011,A19,m,34,1,2012-06-12 10:00:00,2011-12-01 16:21:00,E,101,228.0,1,3.0
2,1,3222,2011,A19,m,34,1,2012-02-20 10:00:00,2011-12-01 16:21:00,E,101,228.0,0,3.0
3,1,8930,2011,A19,m,34,1,2011-12-02 16:21:00,2011-12-01 16:21:00,E,101,228.0,4,3.0
4,2,568302,2011,D25,w,31,1,2011-12-28 08:35:00,2011-12-27 09:45:00,E,101,9.0,2,1.0
5,2,557801,2011,D25,w,31,1,2011-12-28 08:35:00,2011-12-27 09:45:00,E,101,9.0,2,1.0
6,3,5822a2,2011,M17,w,73,1,2011-12-29 08:36:00,2011-12-28 06:00:00,E,101,13.0,3,2.0
7,3,85500,2011,M17,w,73,1,2011-12-30 06:00:00,2011-12-28 06:00:00,E,101,13.0,4,2.0
8,4,5793af,2011,S72,w,75,1,2011-12-14 11:45:00,2011-12-13 17:44:00,N,107,21.0,2,1.0
9,4,579426,2011,S72,w,75,1,2011-12-14 11:45:00,2011-12-13 17:44:00,N,107,21.0,2,1.0
10,4,57933k,2011,S72,w,75,1,2011-12-22 11:30:00,2011-12-13 17:44:00,N,107,21.0,3,1.0
11,4,3806,2011,S72,w,75,1,2011-12-14 10:00:00,2011-12-13 17:44:00,N,107,21.0,2,1.0
12,4,8800c0,2011,S72,w,75,1,2011-12-14 16:00:00,2011-12-13 17:44:00,N,107,21.0,2,1.0
13,4,85501,2011,S72,w,75,1,2011-12-15 10:00:00,2011-12-13 17:44:00,N,107,21.0,3,1.0
14,4,92000,2011,S72,w,75,1,2011-12-16 06:00:00,2011-12-13 17:44:00,N,107,21.0,4,1.0
15,6,8153,2011,C56,w,77,1,2011-12-17 10:18:00,2011-12-15 20:45:00,E,107,17.0,5,3.0
16,6,53995,2011,C56,w,77,1,2011-12-23 11:20:00,2011-12-15 20:45:00,E,107,17.0,4,3.0
17,6,89822,2011,C56,w,77,1,2011-12-15 20:45:00,2011-12-15 20:45:00,E,107,17.0,3,3.0
18,7,3802,2011,M54,w,76,1,2011-12-19 10:00:00,2011-12-16 09:48:00,E,107,21.0,0,4.0
19,8,1632,2011,I50,w,72,1,2011-12-20 10:57:00,2011-12-17 15:49:00,N,107,17.0,1,5.0
20,9,1632,2011,A41,w,84,1,2011-12-27 11:40:00,2011-12-18 18:05:00,N,107,17.0,1,6.0
21,9,551111,2011,A41,w,84,1,2011-12-30 13:05:00,2011-12-18 18:05:00,N,107,17.0,4,6.0
22,9,85501,2011,A41,w,84,1,2011-12-20 00:00:00,2011-12-18 18:05:00,N,107,17.0,1,6.0
23,9,3225,2011,A41,w,84,1,2011-12-28 10:00:00,2011-12-18 18:05:00,N,107,17.0,2,6.0
24,9,8930,2011,A41,w,84,1,2011-12-18 18:05:00,2011-12-18 18:05:00,N,107,17.0,6,6.0
25,9,3200,2011,A41,w,84,1,2011-12-18 18:30:00,2011-12-18 18:05:00,N,107,17.0,6,6.0
26,9,3200,2011,A41,w,84,1,2011-12-19 21:00:00,2011-12-18 18:05:00,N,107,17.0,0,6.0
27,10,1844,2011,I50,w,79,1,2011-12-22 13:17:00,2011-12-19 11:24:00,E,101,13.0,3,0.0
28,10,81521,2011,I50,w,79,1,2011-12-27 14:29:00,2011-12-19 11:24:00,E,101,13.0,1,0.0
29,10,1632,2011,I50,w,79,1,2011-12-28 17:16:00,2011-12-19 11:24:00,E,101,13.0,2,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020562,381373,89820,2016,J44,m,77,2,2016-06-22 14:26:00,NaT,N,107,NaN,2,NaN
1020563,381373,940140,2016,J44,m,77,2,2016-06-24 09:45:00,NaT,N,107,NaN,4,NaN
1020564,381374,3200,2016,R42,w,85,2,2016-06-24 14:30:00,NaT,N,107,NaN,4,NaN
1020565,381375,3225,2016,K86,m,52,2,2016-06-24 12:45:00,NaT,N,107,NaN,4,NaN
1020566,381377,16320,2016,I21,w,80,2,2016-06-23 09:06:00,NaT,N,107,NaN,3,NaN
1020567,381377,1440a,2016,I21,w,80,2,2016-06-23 09:06:00,NaT,N,107,NaN,3,NaN
1020568,381378,3203,2016,S32,w,84,2,2016-06-24 09:45:00,NaT,N,107,NaN,4,NaN
1020569,381380,57873v,2016,S92,m,50,2,2016-06-24 08:15:00,NaT,E,101,NaN,4,NaN
1020570,381381,16320,2016,K22,m,64,2,2016-06-23 12:40:00,NaT,N,107,NaN,3,NaN
1020571,381383,3225,2016,K57,m,61,2,2016-06-24 12:55:00,NaT,N,107,NaN,4,NaN
1020572,381384,3203,2016,S06,w,19,2,2016-06-23 17:30:00,NaT,N,107,NaN,3,NaN
1020573,381384,3200,2016,S06,w,19,2,2016-06-23 17:30:00,NaT,N,107,NaN,3,NaN
1020574,381385,3222,2016,R06,w,58,2,2016-06-24 09:00:00,NaT,N,107,NaN,4,NaN
1020575,381386,3202,2016,S22,m,53,2,2016-06-26 12:45:00,NaT,N,107,NaN,6,NaN
1020576,381387,898e0,2016,E86,m,88,2,2016-06-25 12:42:00,NaT,N,107,NaN,5,NaN
1020577,381394,16320,2016,K80,m,52,2,2016-06-28 07:41:00,NaT,N,107,NaN,1,NaN
1020578,381394,1440a,2016,K80,m,52,2,2016-06-28 07:41:00,NaT,N,107,NaN,1,NaN
1020579,381395,3225,2016,N39,w,82,2,2016-06-27 10:45:00,NaT,N,107,NaN,0,NaN
1020580,381396,3203,2016,S22,m,32,2,2016-06-26 17:00:00,NaT,N,107,NaN,6,NaN
1020581,381397,3225,2016,K29,m,50,2,2016-06-27 12:55:00,NaT,N,107,NaN,0,NaN
1020582,381397,16320,2016,K29,m,50,2,2016-06-28 07:42:00,NaT,N,107,NaN,1,NaN
1020583,381397,1440a,2016,K29,m,50,2,2016-06-28 07:42:00,NaT,N,107,NaN,1,NaN
1020584,381399,898e0,2016,C34,m,68,2,2016-06-27 07:58:00,NaT,N,107,NaN,0,NaN
1020585,381399,940140,2016,C34,m,68,2,2016-06-27 09:45:00,NaT,N,107,NaN,0,NaN
1020586,381400,898e0,2016,B99,m,76,2,2016-06-27 09:00:00,NaT,N,107,NaN,0,NaN
1020587,381401,3200,2016,G08,w,72,2,2016-06-27 12:15:00,NaT,N,107,NaN,0,NaN
1020588,381402,3203,2016,M54,m,53,2,2016-06-28 12:30:00,NaT,N,107,NaN,1,NaN
1020589,381403,537851,2016,Z45,w,87,2,2016-06-28 09:33:00,NaT,E,101,NaN,1,NaN
1020590,381405,12752,2016,I49,w,74,2,2016-06-29 13:45:00,NaT,N,107,NaN,2,NaN
1020591,381405,883bc6,2016,I49,w,74,2,2016-06-29 13:45:00,NaT,N,107,NaN,2,NaN